### PR TITLE
BUG: Remove default maxWidth for EditDialog

### LINKED ISSUE #132: Don't use default maxWidth on edit dialog
The styling of an edit dialog component is defined in `styles/common.ts`, in `EditDialog`. Attributes to styled-components is used for the `minWidth` and `maxWidth` CSS properties, with default values (`10em` and `20em` respectively). For pages using an edit dialog this allows for setting specific values for these width properties, with default values used otherwise.

While it makes sense to have a default value for the minimum width of an edit dialog, having a default maximum width is problematic. If the page using an edit dialog doesn't explicitly set a value for this, the dialog will get the default value of `20em`. This is quite narrow, and leads to the page having to set an arbitrary high value so as to override the default value.

There shouldn't be defined a default value for maximum width. When deciding the width of the edit dialog, the browser will usually set this based on the content of the dialog. If there is a page with a special need to control the width of the dialog, it can be set in the page itself, when specifying the edit dialog attributes - using `width` or `maxWidth` which will be sent on the EDS `Dialog` component. Thus, specifying attributes as part of the styled component (ie. extra attributes, prefixed with `$`) is mostly used for those cases where there is a need for a default value, and that this value can be overridden.

Update 2025-12-02:
The component is using attributes with default values. The way default values are handled should be updated, to be consistent with how it's done for other components (`PageHeader` and  `PageText`):

```typescript
export const EditDialog = styled(Dialog).attrs<{
  $minWidth?: string;
}>(({ $minWidth = "10em" }) => ({
  style: {
    minWidth: $minWidth,
  },
}))`

...

`;
```

Update 2026-02-18:
A new attribute has been added to the component: `extraPaddingBottom`, with a default value of `true`. The attribute and default value is currently defined in the old way, to be consistent with other attribute definitions, but this should be updated to the new format as part of this issue.

### PR DESCRIPTION
**Pull request by nourinmohd**
Resolves #132 and #253. 

Added a `GenericDialog `component and extended the padding bottom to `EditDialog`. 

## Checklist

- [ ] Tests added (if not, comment why)
- [ ] Test coverage equal or up from main (run pytest with `--cov=src/ --cov-report term-missing`)
- [x] If not squash merging, every commit passes tests
- [x] Appropriate [commit prefix](https://upgraded-funicular-eywe4gy.pages.github.io/developing/#commit-prefixes) and precise commit message used
- [x] All debug prints and unnecessary comments removed
- [x] Docstrings are correct and updated
- [x] Documentation is updated, if necessary
- [x] Latest main rebased/merged into branch
- [x] Added comments on this PR where appropriate to help reviewers
- [x] Moved issue status on project board
- [x] Checked the boxes in this checklist ✅

### CODE REVIEW

File: frontend/src/components/Header.tsx [hunk 1]
```diff
@@ -110,7 +110,7 @@ function FeedbackDialog() {
         isDismissable={true}
         open={isOpen}
         onClose={closeDialog}
-        $maxWidth="32em"
+        style={{ maxWidth: "32em" }}
```
Comment (nourinmohd) [inline frontend/src/components/Header.tsx]: I am not sure if this is correct, there are other places that also needs to be changed that uses the EditDialog component. If this is the right way, then I'll make another commit with the respective changes.

**Comment by joargr** [comment]
The `EditDialog` component now has a new attribute `extraPaddingBottom`, with a default value of `true`. The definition of this should be updated as well, as described in the issue.
