### PR TITLE
BUG: Add the empty option to masterdata initial value check

### LINKED ISSUE #125: Initial select option error message when editing empty masterdata
When editing empty masterdata the option lists of the coordinate system and stratigraphic column form fields are empty, except for the "(none)" entries. The form shows an error saying that the "(none)" option does not exist. There is however such an option. This needs to be fixed.

### PR DESCRIPTION
**Pull request by joargr**
Resolves #125 

Fixes the bug by adding the empty option to the check of initial value in the select options list. Also renames some types for better consistency.

## Checklist

- [X] Tests added - not relevant
- [ ] Test coverage equal or up from main (run pytest with `--cov=src/ --cov-report term-missing`)
- [X] If not squash merging, every commit passes tests
- [X] Appropriate [commit prefix](https://upgraded-funicular-eywe4gy.pages.github.io/developing/#commit-prefixes) and precise commit message used
- [X] All debug prints and unnecessary comments removed
- [X] Docstrings are correct and updated
- [X] Documentation is updated, if necessary
- [X] Latest main rebased/merged into branch
- [ ] Added comments on this PR where appropriate to help reviewers
- [X] Moved issue status on project board
- [X] Checked the boxes in this checklist ✅

### CODE REVIEW

File: frontend/src/components/project/masterdata/Edit.tsx [hunk 1]
```diff
@@ -209,14 +209,14 @@ function createItemLists(
...
+  array: IdentifierUuidType[],
   initialValue: IdentifierUuidType,
 ): void {
   setFieldMeta(field, (meta) => ({
     ...meta,
     errorMap: {
-      onChange: findOptionValueInIdentifierUuidArray(
-        identifierUuidArray,
+      onChange: findOptionValueInNameUuidArray(
+        [emptyIdentifierUuid(), ...array],
```
Comment (tnatt) [inline frontend/src/components/project/masterdata/Edit.tsx]: This change here means that an empty value is permitted to submit and the API will respond with a validation error. Is it possible to make it more clear to the user that this actually is a required field. Maybe by splitting the validation for an empty string and the other options?

Comment (joargr) [reply frontend/src/components/project/masterdata/Edit.tsx]: Perhaps validation should be a separate topic for discussion. Should there be some validation in the GUI, or is it best to only let the API to do that? And what form fields should have validation - is it ok to save the masterdata with no fields (assets), or is it required to have at least one field?

Comment (tnatt) [reply frontend/src/components/project/masterdata/Edit.tsx]: Yes agree, we should align on one way of doing it. 
It was actually a bit puzzling to me that it is allowed to save the masterdata without many of these items, I thought all were required. And my guess is that it is not the intended behavior, and we should revisit the [SMDA model]( https://github.com/equinor/fmu-datamodels/blob/003dc98038a4e2fe72f1094d6a5e34bcda05a107/src/fmu/datamodels/fmu_results/fields.py#L344) and add a length requirement to all fields of list type.

**Review by tnatt — APPROVED** [review]
This looks good 👍 
We should however decide how validation on these input fields happen (GUI validation or API response), and look into if the model used to validate the data needs an update. I'll make an issue in `fmu-datamodels`
